# Generated by Django 5.1.5 on 2025-02-14 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_writer',
            new_name='is_creator',
        ),
    ]
