# Generated by Django 4.2.8 on 2025-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_rename_is_writer_customuser_is_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_creator',
            field=models.BooleanField(default=False, verbose_name='Are you a content creator?'),
        ),
    ]
