# Generated by Django 4.2.8 on 2025-02-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_customuser_is_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_unlimited_access',
            field=models.BooleanField(default=False, verbose_name='Has Unlimited Access?'),
        ),
    ]
