# Generated by Django 4.2.8 on 2025-02-20 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_customuser_has_unlimited_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='has_unlimited_access',
            new_name='unlimited_access_membership',
        ),
    ]
