# Generated by Django 4.2.8 on 2025-02-20 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='membership_name',
            new_name='member_name',
        ),
    ]
