# Generated by Django 4.2.8 on 2025-02-25 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_alter_article_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
