<<<<<<< HEAD
# Generated by Django 4.2.8 on 2025-02-25 14:23
=======
# Generated by Django 4.2.8 on 2025-02-25 01:02
>>>>>>> 9db95efb8e3c3ad66f5385c45b0c93387a5959e2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=10000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='article_images/')),
                ('user', models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator_articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
