# Generated by Django 4.2.8 on 2025-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='Only for Unlimited Access subscribers?'),
        ),
    ]
