# Generated by Django 4.2.8 on 2025-02-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_alter_article_is_unlimited'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_unlimited',
            field=models.BooleanField(default=False, verbose_name='Only for Unlimited Access member?'),
        ),
    ]
