# Generated by Django 4.2.8 on 2025-02-28 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_article_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='free_teaser',
            field=models.BooleanField(default=False, help_text='Allow this article to be viewed without login'),
        ),
    ]
