# Generated by Django 4.2.8 on 2025-02-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_article_free_teaser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='free_teaser',
        ),
    ]
