# Generated by Django 4.2.8 on 2025-02-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_remove_article_free_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='free_teaser',
            field=models.BooleanField(default=False, help_text='Allow this article to be viewed without login'),
        ),
    ]
