# Generated by Django 4.2.8 on 2025-02-28 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0006_article_free_teaser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='free_teaser',
            new_name='free_article',
        ),
    ]
