# Generated by Django 4.2.8 on 2025-02-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_rename_free_teaser_article_free_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='free_article',
            new_name='article_teaser',
        ),
    ]
