# Generated by Django 4.2.8 on 2025-03-03 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_rename_free_article_article_article_teaser'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='event_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='event_venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='is_event_related',
            field=models.BooleanField(default=False, help_text='Is this article related to an event?'),
        ),
    ]
