# Generated by Django 4.2.8 on 2025-03-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0009_article_event_date_article_event_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event_postcode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
