# Generated by Django 4.2.8 on 2025-03-03 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_article_event_postcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='event_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
