# Generated by Django 4.2.8 on 2025-04-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0014_alter_article_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='event_postcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
